[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'
hook_add = '''
let g:dps_ghosttext#ftmap = {
\  "qiita.com": "markdown"
\}
'''

[[plugins]]
repo = 'skanehira/denops-docker.vim'

[[plugins]]
repo = 'vim-skk/denops-skkeleton.vim'
hook_add = '''
  autocmd User skkeleton-enable-pre let b:coc_suggest_disable = v:true
  autocmd User skkeleton-disable-pre let b:coc_suggest_disable = v:false
  imap <C-j> <Plug>(skkeleton-toggle)
  cmap <C-j> <Plug>(skkeleton-toggle)
  autocmd User skkeleton-initialize-post call skkeleton#config({"eggLikeNewline": v:true, "keepState": v:true})
  if has('mac')
    autocmd User skkeleton-initialize-post call skkeleton#config({"globalJisyo": expand("~/Library/Application Support/AquaSKK/SKK-JISYO.L")})
  else
  endif
  call skkeleton#register_kanatable('rom', {
    \ "z\<Space>": ["\u3000", ''],
    \ "z,": ['―', ''],
    \ "<<": ['《', ''],
    \ ">>": ['》', ''],
    \ "(": ['（', ''],
    \ ")": ["）", ''],
    \ "z|": ['｜', ''],
  \ })
'''
